apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-worker
  template:
    metadata:
      labels:
        app: task-worker
    spec:
      containers:
        - name: worker
          image: task-worker:latest
          env:
            - name: DATABASE_URL
              value: "postgresql://myuser:mypassword@postgres-service:5432/mydb"
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@localhost/"
